# Generated by Django 4.2.2 on 2023-06-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateField()),
                ('saida', models.DateField()),
            ],
            options={
                'db_table': 'acomodacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Joga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('cor', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'joga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entradas_vendidas', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
            options={
                'db_table': 'jogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeioComunicacaoSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio_comunicacao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'meio_comunicacao_salao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movimento', models.IntegerField()),
                ('jogada', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'movimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_clubes', models.IntegerField()),
                ('nome_pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipaCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campeonato', models.CharField(max_length=50)),
                ('tipo_participacao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'participa_campeonato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('idParticipante', models.AutoField(db_column='IdParticipante', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
                ('endereco', models.CharField(db_column='Endereco', max_length=100)),
                ('telefone', models.CharField(db_column='Telefone', max_length=20)),
                ('tipo_participante', models.CharField(db_column='TipoParticipante', max_length=50)),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'db_table': 'salao',
                'managed': False,
            },
        ),
    ]
